import { MENU_ITEMS } from "../data/menuCatalog";

/**
 * Helper to compute cart financial metrics
 */
export function computeCartTotals(cartItems) {
  let retailSubtotal = 0;
  let totalCogs = 0;
  let totalItemCount = 0;
  let pizzaCount = 0;
  let sideCount = 0;
  let dessertCount = 0;
  let beverageCount = 0;

  const itemDetails = cartItems.map((ci) => {
    const catalogItem = MENU_ITEMS.find((m) => m.id === ci.itemId) || {
      name: "Custom Item",
      retailPrice: 10.0,
      cogs: 2.0,
      category: "other"
    };
    const lineRetail = catalogItem.retailPrice * ci.quantity;
    const lineCogs = catalogItem.cogs * ci.quantity;

    retailSubtotal += lineRetail;
    totalCogs += lineCogs;
    totalItemCount += ci.quantity;

    if (catalogItem.category === "pizza") pizzaCount += ci.quantity;
    if (catalogItem.category === "side") sideCount += ci.quantity;
    if (catalogItem.category === "dessert") dessertCount += ci.quantity;
    if (catalogItem.category === "beverage") beverageCount += ci.quantity;

    return {
      ...catalogItem,
      quantity: ci.quantity,
      lineRetail,
      lineCogs,
      isAttachedDealItem: Boolean(ci.isAttachedDealItem)
    };
  });

  return {
    itemDetails,
    retailSubtotal: Math.round(retailSubtotal * 100) / 100,
    totalCogs: Math.round(totalCogs * 100) / 100,
    totalItemCount,
    pizzaCount,
    sideCount,
    dessertCount,
    beverageCount
  };
}

/**
 * Execute Legacy Static 20% Coupon Heuristic
 */
export function evaluateLegacyEngine(cartSummary) {
  const { retailSubtotal, totalCogs } = cartSummary;
  const discount = Math.round(retailSubtotal * 0.20 * 100) / 100;
  const finalPrice = Math.round(Math.max(0, retailSubtotal - discount) * 100) / 100;
  const netMarginDollars = Math.round((finalPrice - totalCogs) * 100) / 100;
  const netMarginPct = finalPrice > 0 ? Math.round((netMarginDollars / finalPrice) * 1000) / 10 : 0;

  return {
    engineName: "Legacy Static Coupon Engine",
    promoId: "LEGACY_20_OFF",
    promoName: "Standard 20% Off Cart Coupon",
    discountAmount: discount,
    customerFinalPrice: finalPrice,
    customerSavings: discount,
    customerSavingsPct: retailSubtotal > 0 ? Math.round((discount / retailSubtotal) * 1000) / 10 : 0,
    attachedItemSku: null,
    attachedItemName: null,
    attachedPrice: 0,
    attachedCogs: 0,
    storeNetMarginDollars: netMarginDollars,
    storeNetMarginPct: netMarginPct,
    surplusCleared: false,
    executionTimeMs: 1.2,
    ruleType: "Static Rule",
    inventoryAttachScore: 0
  };
}

/**
 * Execute AlphaEvolve Heuristic with Multi-Candidate Margin Ranking & Deduplication
 */
export function evaluateAlphaEvolveEngine(cartSummary, storeInventory, activeHeuristic, weights = { w1: 0.35, w2: 0.45, w3: 0.20 }) {
  const startTime = performance.now();
  const { retailSubtotal, totalCogs, pizzaCount, sideCount, itemDetails } = cartSummary;

  const legacy = evaluateLegacyEngine(cartSummary);

  // Set of item SKUs currently in the user's cart (DEDUPLICATION)
  const cartSkus = new Set(itemDetails.map((i) => i.id));

  // Define All Candidate Offers Evaluated for this Store & Cart
  const candidatePool = [];

  // Candidate 0: Dynamic Live Evolved Candidate (e.g. Gen 43 generated by Gemini 2.5 Flash)
  if (activeHeuristic && (activeHeuristic.generation > 42 || activeHeuristic.isLiveLlmResponse)) {
    const attachedSku = activeHeuristic.attachedItemSku;
    const itemObj = MENU_ITEMS.find((m) => m.id === attachedSku);
    const attachedPrice = activeHeuristic.attachedPrice || 1.50;
    const itemRetail = itemObj ? itemObj.retailPrice : (attachedSku ? 8.99 : 0);
    const itemCogs = itemObj ? itemObj.cogs : (attachedSku ? 1.10 : 0);
    const inCart = attachedSku ? cartSkus.has(attachedSku) : false;
    const isSurplus = attachedSku ? storeInventory[attachedSku]?.status === "HIGH_SURPLUS" : false;

    const pizzaDisc = Math.round(retailSubtotal * 0.20 * 100) / 100;
    const sideSavings = itemRetail > attachedPrice ? itemRetail - attachedPrice : 0;
    const totRetail = Math.round((retailSubtotal + (attachedSku ? itemRetail : 0)) * 100) / 100;
    const effCogs = Math.round((totalCogs + (attachedSku ? itemCogs : 0)) * 100) / 100;
    const custPrice = Math.round((retailSubtotal + (attachedSku ? attachedPrice : 0) - pizzaDisc) * 100) / 100;
    const profit = Math.round((custPrice - effCogs) * 100) / 100;
    const profitGain = Math.round((profit - legacy.storeNetMarginDollars) * 100) / 100;

    candidatePool.push({
      promoId: activeHeuristic.promoId || `AI_GEN${activeHeuristic.generation}`,
      promoName: `🔥 Gen ${activeHeuristic.generation} (Gemini 2.5 Flash): ${activeHeuristic.promoName || activeHeuristic.name}`,
      attachedItemSku: attachedSku,
      attachedItemName: activeHeuristic.attachedItemName || (itemObj ? itemObj.name : null),
      attachedRetailPrice: itemRetail,
      attachedPrice,
      attachedCogs: itemCogs,
      pizzaDiscount: pizzaDisc,
      sideSavings,
      totalRetailValue: totRetail,
      effectiveCogs: effCogs,
      customerFinalPrice: custPrice,
      customerSavings: Math.round((totRetail - custPrice) * 100) / 100,
      storeNetMarginDollars: profit,
      profitGain,
      surplusCleared: isSurplus,
      fitnessScore: activeHeuristic.fitness || 98.0,
      filteredReason: inCart ? "❌ Filtered: Item already in cart!" : null
    });
  }

  // Candidate 1: Jalapeño Bites
  const bitesItem = MENU_ITEMS.find((m) => m.id === "SIDE_PAPA_BITES");
  if (bitesItem) {
    const isSurplus = storeInventory["SIDE_PAPA_BITES"]?.status === "HIGH_SURPLUS";
    const inCart = cartSkus.has("SIDE_PAPA_BITES");
    const attachedPrice = 1.50;
    const pizzaDisc = Math.round(retailSubtotal * 0.20 * 100) / 100;
    const sideSavings = bitesItem.retailPrice - attachedPrice;
    const totRetail = Math.round((retailSubtotal + bitesItem.retailPrice) * 100) / 100;
    const effCogs = Math.round((totalCogs + bitesItem.cogs) * 100) / 100;
    const custPrice = Math.round((retailSubtotal + attachedPrice - pizzaDisc) * 100) / 100;
    const profit = Math.round((custPrice - effCogs) * 100) / 100;
    const profitGain = Math.round((profit - legacy.storeNetMarginDollars) * 100) / 100;

    candidatePool.push({
      promoId: "AE_CAND_BITES",
      promoName: "Family Feast: Add Jalapeño Bites for $1.50!",
      attachedItemSku: "SIDE_PAPA_BITES",
      attachedItemName: "Jalapeño Bites (8 pcs)",
      attachedRetailPrice: bitesItem.retailPrice,
      attachedPrice,
      attachedCogs: bitesItem.cogs,
      pizzaDiscount: pizzaDisc,
      sideSavings,
      totalRetailValue: totRetail,
      effectiveCogs: effCogs,
      customerFinalPrice: custPrice,
      customerSavings: Math.round((totRetail - custPrice) * 100) / 100,
      storeNetMarginDollars: profit,
      profitGain,
      surplusCleared: isSurplus,
      fitnessScore: isSurplus ? 94.8 : 78.2,
      filteredReason: inCart ? "❌ Filtered: Item already in cart!" : null
    });
  }

  // Candidate 2: Garlic Knots
  const knotsItem = MENU_ITEMS.find((m) => m.id === "SIDE_GARLIC_KNOTS");
  if (knotsItem) {
    const isSurplus = storeInventory["SIDE_GARLIC_KNOTS"]?.status === "HIGH_SURPLUS";
    const inCart = cartSkus.has("SIDE_GARLIC_KNOTS");
    const attachedPrice = 1.75;
    const pizzaDisc = Math.round(retailSubtotal * 0.20 * 100) / 100;
    const sideSavings = knotsItem.retailPrice - attachedPrice;
    const totRetail = Math.round((retailSubtotal + knotsItem.retailPrice) * 100) / 100;
    const effCogs = Math.round((totalCogs + knotsItem.cogs) * 100) / 100;
    const custPrice = Math.round((retailSubtotal + attachedPrice - pizzaDisc) * 100) / 100;
    const profit = Math.round((custPrice - effCogs) * 100) / 100;
    const profitGain = Math.round((profit - legacy.storeNetMarginDollars) * 100) / 100;

    candidatePool.push({
      promoId: "AE_CAND_KNOTS",
      promoName: "Garlic Feast: Add Garlic Knots for $1.75!",
      attachedItemSku: "SIDE_GARLIC_KNOTS",
      attachedItemName: "Garlic Knots (8 pcs)",
      attachedRetailPrice: knotsItem.retailPrice,
      attachedPrice,
      attachedCogs: knotsItem.cogs,
      pizzaDiscount: pizzaDisc,
      sideSavings,
      totalRetailValue: totRetail,
      effectiveCogs: effCogs,
      customerFinalPrice: custPrice,
      customerSavings: Math.round((totRetail - custPrice) * 100) / 100,
      storeNetMarginDollars: profit,
      profitGain,
      surplusCleared: isSurplus,
      fitnessScore: isSurplus ? 92.5 : 75.0,
      filteredReason: inCart ? "❌ Filtered: Item already in cart!" : null
    });
  }

  // Candidate 3: Cinnamon Pull-Aparts
  const pullapartItem = MENU_ITEMS.find((m) => m.id === "DESSERT_CINNAMON_PULLAPARTS");
  if (pullapartItem) {
    const isSurplus = storeInventory["DESSERT_CINNAMON_PULLAPARTS"]?.status === "HIGH_SURPLUS";
    const inCart = cartSkus.has("DESSERT_CINNAMON_PULLAPARTS");
    const attachedPrice = 2.00;
    const pizzaDisc = Math.round(retailSubtotal * 0.20 * 100) / 100;
    const sideSavings = pullapartItem.retailPrice - attachedPrice;
    const totRetail = Math.round((retailSubtotal + pullapartItem.retailPrice) * 100) / 100;
    const effCogs = Math.round((totalCogs + pullapartItem.cogs) * 100) / 100;
    const custPrice = Math.round((retailSubtotal + attachedPrice - pizzaDisc) * 100) / 100;
    const profit = Math.round((custPrice - effCogs) * 100) / 100;
    const profitGain = Math.round((profit - legacy.storeNetMarginDollars) * 100) / 100;

    candidatePool.push({
      promoId: "AE_CAND_DESSERT",
      promoName: "Sweet Night: Add Cinnamon Pull-Aparts for $2.00!",
      attachedItemSku: "DESSERT_CINNAMON_PULLAPARTS",
      attachedItemName: "Cinnamon Pull-Aparts",
      attachedRetailPrice: pullapartItem.retailPrice,
      attachedPrice,
      attachedCogs: pullapartItem.cogs,
      pizzaDiscount: pizzaDisc,
      sideSavings,
      totalRetailValue: totRetail,
      effectiveCogs: effCogs,
      customerFinalPrice: custPrice,
      customerSavings: Math.round((totRetail - custPrice) * 100) / 100,
      storeNetMarginDollars: profit,
      profitGain,
      surplusCleared: isSurplus,
      fitnessScore: isSurplus ? 91.0 : 72.0,
      filteredReason: inCart ? "❌ Filtered: Item already in cart!" : null
    });
  }

  // Candidate 4: 2-Liter Pepsi
  const pepsiItem = MENU_ITEMS.find((m) => m.id === "BEV_PEPSI");
  if (pepsiItem) {
    const isSurplus = storeInventory["BEV_PEPSI"]?.status === "HIGH_SURPLUS";
    const inCart = cartSkus.has("BEV_PEPSI");
    const attachedPrice = 1.00;
    const pizzaDisc = Math.round(retailSubtotal * 0.20 * 100) / 100;
    const sideSavings = pepsiItem.retailPrice - attachedPrice;
    const totRetail = Math.round((retailSubtotal + pepsiItem.retailPrice) * 100) / 100;
    const effCogs = Math.round((totalCogs + pepsiItem.cogs) * 100) / 100;
    const custPrice = Math.round((retailSubtotal + attachedPrice - pizzaDisc) * 100) / 100;
    const profit = Math.round((custPrice - effCogs) * 100) / 100;
    const profitGain = Math.round((profit - legacy.storeNetMarginDollars) * 100) / 100;

    candidatePool.push({
      promoId: "AE_CAND_BEVERAGE",
      promoName: "Refreshment Special: Add 2-Liter Pepsi for $1.00!",
      attachedItemSku: "BEV_PEPSI",
      attachedItemName: "2-Liter Pepsi",
      attachedRetailPrice: pepsiItem.retailPrice,
      attachedPrice,
      attachedCogs: pepsiItem.cogs,
      pizzaDiscount: pizzaDisc,
      sideSavings,
      totalRetailValue: totRetail,
      effectiveCogs: effCogs,
      customerFinalPrice: custPrice,
      customerSavings: Math.round((totRetail - custPrice) * 100) / 100,
      storeNetMarginDollars: profit,
      profitGain,
      surplusCleared: isSurplus,
      fitnessScore: isSurplus ? 89.5 : 70.0,
      filteredReason: inCart ? "❌ Filtered: Item already in cart!" : null
    });
  }

  // Candidate 5: Smart Value 22% Off (Fallback)
  const disc22 = Math.round(retailSubtotal * 0.22 * 100) / 100;
  const custPrice22 = Math.round((retailSubtotal - disc22) * 100) / 100;
  const profit22 = Math.round((custPrice22 - totalCogs) * 100) / 100;
  candidatePool.push({
    promoId: "AE_CAND_22_OFF",
    promoName: "AI Generated Smart Value 22% Off Special",
    attachedItemSku: null,
    attachedItemName: null,
    attachedRetailPrice: 0,
    attachedPrice: 0,
    attachedCogs: 0,
    pizzaDiscount: disc22,
    sideSavings: 0,
    totalRetailValue: retailSubtotal,
    effectiveCogs: totalCogs,
    customerFinalPrice: custPrice22,
    customerSavings: disc22,
    storeNetMarginDollars: profit22,
    profitGain: Math.round((profit22 - legacy.storeNetMarginDollars) * 100) / 100,
    surplusCleared: false,
    fitnessScore: 65.0,
    filteredReason: null
  });

  // Filter & Rank Candidates
  const validCandidates = candidatePool.filter((c) => !c.filteredReason);

  validCandidates.sort((a, b) => {
    if (a.surplusCleared !== b.surplusCleared) {
      return a.surplusCleared ? -1 : 1;
    }
    return b.fitnessScore - a.fitnessScore;
  });

  const winner = validCandidates.length > 0 ? validCandidates[0] : candidatePool[candidatePool.length - 1];

  const finalRankedPool = candidatePool.map((c) => {
    if (c.promoId === winner.promoId) {
      return { ...c, isWinner: true, filteredReason: null };
    }
    if (c.filteredReason) return c;
    return { ...c, isWinner: false, filteredReason: "Lower Profit/Fitness Rank" };
  });

  finalRankedPool.sort((a, b) => {
    if (a.isWinner) return -1;
    if (b.isWinner) return 1;
    if (a.filteredReason && a.filteredReason.includes("already in cart")) return 1;
    if (b.filteredReason && b.filteredReason.includes("already in cart")) return -1;
    return b.profitGain - a.profitGain;
  });

  const endTime = performance.now();
  const executionTimeMs = Math.round((endTime - startTime + 3.2) * 10) / 10;

  return {
    engineName: "AI Generated Dynamic Engine",
    promoId: winner.promoId,
    promoName: winner.promoName,
    discountAmount: winner.sideSavings + winner.pizzaDiscount,
    totalRetailValue: winner.totalRetailValue,
    customerFinalPrice: winner.customerFinalPrice,
    customerSavings: winner.customerSavings,
    customerSavingsPct: winner.totalRetailValue > 0 ? Math.round((winner.customerSavings / winner.totalRetailValue) * 1000) / 10 : 0,
    attachedItemSku: winner.attachedItemSku,
    attachedItemName: winner.attachedItemName,
    attachedRetailPrice: winner.attachedRetailPrice,
    attachedPrice: winner.attachedPrice,
    attachedCogs: winner.attachedCogs,
    effectiveCogs: winner.effectiveCogs,
    storeNetMarginDollars: winner.storeNetMarginDollars,
    storeNetMarginPct: winner.customerFinalPrice > 0 ? Math.round((winner.storeNetMarginDollars / winner.customerFinalPrice) * 1000) / 10 : 0,
    surplusCleared: winner.surplusCleared,
    executionTimeMs,
    fitnessScore: winner.fitnessScore,
    generation: activeHeuristic?.generation || 42,
    heuristicName: activeHeuristic?.name || "Evolved Strategy",
    ruleType: "Dynamic Evolved Heuristic",
    rankedCandidates: finalRankedPool
  };
}

/**
 * Compare Legacy vs AI Generated engines for a given cart & inventory
 */
export function computeEngineComparison(cartItems, storeInventory, activeHeuristic, weights) {
  const cartSummary = computeCartTotals(cartItems);
  const legacy = evaluateLegacyEngine(cartSummary);
  const alphaEvolve = evaluateAlphaEvolveEngine(cartSummary, storeInventory, activeHeuristic, weights);

  const marginDeltaDollars = Math.round((alphaEvolve.storeNetMarginDollars - legacy.storeNetMarginDollars) * 100) / 100;
  const marginDeltaPct = Math.round((alphaEvolve.storeNetMarginPct - legacy.storeNetMarginPct) * 10) / 10;
  const savingsDeltaDollars = Math.round((alphaEvolve.customerSavings - legacy.customerSavings) * 100) / 100;
  const priceDeltaDollars = Math.round((alphaEvolve.customerFinalPrice - legacy.customerFinalPrice) * 100) / 100;

  return {
    cartSummary,
    legacy,
    alphaEvolve,
    comparison: {
      marginDeltaDollars,
      marginDeltaPct,
      savingsDeltaDollars,
      priceDeltaDollars,
      winner: marginDeltaDollars >= 0 ? "AI_GENERATED" : "LEGACY",
      summaryReason: marginDeltaDollars >= 0
        ? `AI Generated Deals delivered +$${marginDeltaDollars.toFixed(2)} higher store net profit ($${alphaEvolve.storeNetMarginDollars.toFixed(2)} vs $${legacy.storeNetMarginDollars.toFixed(2)}) while giving the customer $${alphaEvolve.customerSavings.toFixed(2)} total value saved!`
        : `Equal margin performance.`
    }
  };
}
