import React, { useState } from "react";
import { DollarSign, TrendingUp, Store, BarChart3 } from "lucide-react";

export function BusinessCalculator({ marginDeltaPerCart = 2.20 }) {
  const [storeCount, setStoreCount] = useState(5000);
  const [ordersPerStorePerDay, setOrdersPerStorePerDay] = useState(120);

  const totalDailyOrders = storeCount * ordersPerStorePerDay;
  const totalDailyProfitGain = totalDailyOrders * marginDeltaPerCart;
  const totalAnnualProfitGain = totalDailyProfitGain * 365;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      
      {/* Header */}
      <div className="card-panel">
        <div className="panel-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <TrendingUp style={{ width: '22px', height: '22px', color: '#059669' }} />
            <span className="panel-title" style={{ fontSize: '16px' }}>Enterprise Business ROI & Profit Impact Model</span>
          </div>
          <span className="pill-badge pill-badge-green">Financial Impact</span>
        </div>

        <p style={{ fontSize: '12px', color: '#475569', fontWeight: '600' }}>
          Simulate network-wide annual profit expansion generated by AI generated dynamic deals.
        </p>
      </div>

      {/* Sliders Box */}
      <div className="card-panel">
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
          
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
              <span style={{ fontSize: '12px', fontWeight: '800', color: '#000000' }}>Total Store Network Locations</span>
              <span style={{ fontSize: '14px', fontWeight: '900', color: '#059669' }}>{storeCount.toLocaleString()} Stores</span>
            </div>
            <input
              type="range"
              min="100"
              max="10000"
              step="100"
              value={storeCount}
              onChange={(e) => setStoreCount(Number(e.target.value))}
              style={{ width: '100%', accentColor: '#059669', cursor: 'pointer' }}
            />
          </div>

          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '6px' }}>
              <span style={{ fontSize: '12px', fontWeight: '800', color: '#000000' }}>Daily Orders per Store</span>
              <span style={{ fontSize: '14px', fontWeight: '900', color: '#059669' }}>{ordersPerStorePerDay} Orders/Day</span>
            </div>
            <input
              type="range"
              min="10"
              max="500"
              step="5"
              value={ordersPerStorePerDay}
              onChange={(e) => setOrdersPerStorePerDay(Number(e.target.value))}
              style={{ width: '100%', accentColor: '#059669', cursor: 'pointer' }}
            />
          </div>

        </div>
      </div>

      {/* Annual Impact Stat Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px' }}>
        
        <div style={{ background: '#FFFFFF', padding: '16px', borderRadius: '12px', border: '1px solid #CBD5E1' }}>
          <div style={{ fontSize: '11px', color: '#64748B', fontWeight: '800', textTransform: 'uppercase' }}>Daily Network Order Volume</div>
          <div style={{ fontSize: '20px', fontWeight: '900', color: '#000000', marginTop: '4px' }}>
            {totalDailyOrders.toLocaleString()} Orders
          </div>
        </div>

        <div style={{ background: '#FFFFFF', padding: '16px', borderRadius: '12px', border: '1px solid #CBD5E1' }}>
          <div style={{ fontSize: '11px', color: '#64748B', fontWeight: '800', textTransform: 'uppercase' }}>Margin Gain per Order</div>
          <div style={{ fontSize: '20px', fontWeight: '900', color: '#059669', marginTop: '4px' }}>
            +${marginDeltaPerCart.toFixed(2)} / Cart
          </div>
        </div>

        <div style={{ background: '#ECFDF5', padding: '16px', borderRadius: '12px', border: '2px solid #059669' }}>
          <div style={{ fontSize: '11px', color: '#065F46', fontWeight: '900', textTransform: 'uppercase' }}>Projected Annual Profit Gain</div>
          <div style={{ fontSize: '24px', fontWeight: '900', color: '#059669', marginTop: '4px' }}>
            +${(totalAnnualProfitGain / 1000000).toFixed(2)}M / Year
          </div>
        </div>

      </div>

    </div>
  );
}
